databases:
  - name: eventbrite
    user: eventbrite
    plan: free
    region: oregon

services:
  - type: web
    name: eventbrite
    plan: free
    region: oregon
    branch: main
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: eventbrite
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
